# - Default config
#   https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/yazi-default.toml

# - Documentation
#   https://yazi-rs.github.io/docs/configuration/yazi

[mgr]
ratio = [ 1, 3, 3 ]
sort_by = "natural"
show_hidden = true

[tasks]
image_alloc = 0 # - Show images of any size
image_bound = [ 0, 0 ] # - Show images of any size

# - Enable drag and drop
#   https://yazi-rs.github.io/docs/tips#drag-and-drop
[[mgr.prepend_keymap]]
on  = "<C-n>"
run = 'shell -- dragon-drop -x -i -T "$1"'

# - Set as wallpaper option
#   https://yazi-rs.github.io/docs/tips#set-a-wallpaper
[[opener.set-wallpaper]]
run  = 'hyprctl hyprpaper reload ,"$0"'
for  = "linux"
desc = "Set as wallpaper"
[[open.prepend_rules]]
mime = "image/*"
use  = [ "set-wallpaper", "open" ]
