# To learn about sops read its file in the learning repo.

# Key aliases for easier reference
keys:
  - &mabq age120tq73mkdzyjaq544rs9cqkedetzg6y8tu763ax03zvprg8emq5qnd2az2
  # - &jmsb age120...

# The first matching rule wins.
#
# You can define multiple keys for each rule. For more information see
# https://github.com/mic92/sops-nix#usage-example
creation_rules:
  - path_regex: ^secrets/mabq-.*\.json$
    key_groups:
    - age:
      - *mabq

