# https://starship.rs/config/#configuration

format = "$hostname$directory$git_branch$git_status$character"
add_newline = true
command_timeout = 200

[hostname]
ssh_only = true
format = '@[$hostname]($style) '
style = 'bold yellow'

[directory]
truncation_length = 2
truncation_symbol = "…/"
# truncation_length = 99
# truncation_symbol = ""
style = 'bold cyan'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
style = 'italic purple'

[git_status]
format     = '[$all_status]($style) '
style      = 'bold purple'
ahead      = "⇡${count} "
behind     = "⇣${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "

[character]
error_symbol = '[✖](bold red)'
vimcmd_symbol = '[_](bold green)'
vimcmd_replace_one_symbol = '[_](bold green)'
vimcmd_replace_symbol = '[_](bold green)'
vimcmd_visual_symbol = '[_](bold green)'
