# Default config
#   https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/theme-dark.toml

# Improve readability in tabs

[tabs]
inactive = { bg = "reset", fg = "lightyellow" }
active   = { bg = "yellow", fg = "black", italic = true }

sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }
